# Generated by Django 3.1 on 2024-07-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
