# Generated by Django 3.1 on 2024-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brands', '0002_auto_20240705_1517'),
        ('app_subcategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(to='app_brands.Brand'),
        ),
    ]
