# Generated by Django 3.1 on 2024-07-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_brands', '0002_auto_20240705_1517'),
        ('app_subcategory', '0002_auto_20240706_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_brands.brand'),
        ),
    ]
